"""create ioc lookups table

Revision ID: 042fb422f857
Revises: df44cbe5aa63
Create Date: 2026-09-05 03:37:51.191904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '042fb422f857'
down_revision: Union[str, Sequence[str], None] = 'df44cbe5aa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ioc_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lookup_id', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('looked_up_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ioc_lookups_id'), 'ioc_lookups', ['id'], unique=False)
    op.create_index(op.f('ix_ioc_lookups_indicator'), 'ioc_lookups', ['indicator'], unique=False)
    op.create_index(op.f('ix_ioc_lookups_lookup_id'), 'ioc_lookups', ['lookup_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ioc_lookups_lookup_id'), table_name='ioc_lookups')
    op.drop_index(op.f('ix_ioc_lookups_indicator'), table_name='ioc_lookups')
    op.drop_index(op.f('ix_ioc_lookups_id'), table_name='ioc_lookups')
    op.drop_table('ioc_lookups')
    # ### end Alembic commands ###
