"""create phishing submissions table

Revision ID: 27aaffe440ce
Revises: df44cbe5aa63
Create Date: 2026-08-17 14:10:38.914987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27aaffe440ce'
down_revision: Union[str, Sequence[str], None] = 'df44cbe5aa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phishing_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('verdict', sa.Enum('clean', 'suspicious', 'malicious', name='verdict'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'resolved', name='submissionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_submissions_id'), 'phishing_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_phishing_submissions_submission_id'), 'phishing_submissions', ['submission_id'], unique=True)
    op.create_index(op.f('ix_phishing_submissions_submitted_by'), 'phishing_submissions', ['submitted_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phishing_submissions_submitted_by'), table_name='phishing_submissions')
    op.drop_index(op.f('ix_phishing_submissions_submission_id'), table_name='phishing_submissions')
    op.drop_index(op.f('ix_phishing_submissions_id'), table_name='phishing_submissions')
    op.drop_table('phishing_submissions')
    # ### end Alembic commands ###
    # Les types ENUM Postgres ne sont pas supprimes par drop_table : sans cela,
    # un downgrade puis upgrade echoue avec "type verdict already exists".
    sa.Enum(name='verdict').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='submissionstatus').drop(op.get_bind(), checkfirst=True)
